/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CanvasBox: typeof import('./src/components/Canvas/CanvasBox.vue')['default']
    CanvasCabinet: typeof import('./src/components/Canvas/CanvasCabinet.vue')['default']
    CreateStorageModal: typeof import('./src/components/Storage/Modal/CreateStorageModal.vue')['default']
    CreateThingModal: typeof import('./src/components/Thing/Modal/CreateThingModal.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCascader: typeof import('naive-ui')['NCascader']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorageDescription: typeof import('./src/components/Storage/StorageDescription.vue')['default']
    StorageList: typeof import('./src/components/Storage/StorageList.vue')['default']
    ThingDescription: typeof import('./src/components/Thing/ThingDescription.vue')['default']
    ThingList: typeof import('./src/components/Thing/ThingList.vue')['default']
    ThingModal: typeof import('./src/components/Storage/Modal/ThingModal.vue')['default']
    UpdateBoxModal: typeof import('./src/components/Storage/Modal/UpdateBoxModal.vue')['default']
    UpdateCabinetModal: typeof import('./src/components/Storage/Modal/UpdateCabinetModal.vue')['default']
    UpdateThingModal: typeof import('./src/components/Thing/Modal/UpdateThingModal.vue')['default']
  }
}
